apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instance.aliyun.ecs.doslab.io
spec:
  group: aliyun.ecs.doslab.io
  names:
    kind: Instance
    plural: instances
    singular: instance
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Region Id
          jsonPath: .spec.domain.regionId
          name: RegionId
          type: string
        - description: Hostname
          jsonPath: .spec.domain.hostname
          name: Hostname
          type: string
        - description: InstanceId
          jsonPath: .spec.instanceId
          name: InstanceId
          type: string
        - description: InstanceType
          jsonPath: .spec.domain.instanceType
          name: InstanceType
          type: string
        - description: ImageId
          jsonPath: .spec.domain.imageId
          name: ImageId
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          description: VMInstance is the Schema for the vminstances API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: VMInstanceSpec defines the desired state of VMInstance
              properties:
                domain:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                lifeCycle:
                  description: request to be execute
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                #                  meta info
                instanceId:
                  type: string
                regionId:
                  description: regionId
                  type: string
                #                  secret info requeired
                secretRef:
                  description: SrereteRef
                  properties:
                    name:
                      description: secretName
                      type: string
                    namespace:
                      description: secretNamespace
                      type: string
                  required:
                    - name
                    - namespace
                  type: object
              required:
                - secretRef
              type: object
            status:
              description: InstanceStatus defines the observed state of VMInstance
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
