apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openstacknetworks.doslab.io
spec:
  group: doslab.io
  names:
    kind: OpenstackNetwork
    plural: openstacknetworks
    singular: openstacknetwork
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: UUID for the network
          jsonPath: .spec.id
          name: ID
          type: string
        - description: Human-readable name for the network. Might not be unique.
          jsonPath: .spec.domain.name
          name: Name
          type: string
        - description: The administrative state of network. If false (down), the network does not forward packets.
          jsonPath: .spec.domain.admin_state_up
          name: AdminStateUp
          type: boolean
        - description: Indicates whether network is currently operational. Possible values include
          jsonPath: .spec.domain.status
          name: Status
          type: string
        - description: Subnets associated with this network.
          jsonPath: .spec.domain.subnets
          name: Subnets
          type: string
        - description: TenantID is the project owner of the network.
          jsonPath: .spec.domain.tenant_id
          name: TenantID
          type: string
        - description: Specifies whether the network resource can be accessed by any tenant.
          jsonPath: .spec.domain.shared
          name: Shared
          type: boolean
      name: v1
      schema:
        openAPIV3Schema:
          description: network is the Schema for the openstack network API
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: spec defines the desired state of openstack network
              properties:
                domain:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                lifeCycle:
                  description: request to be execute
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                #                  meta info
                id:
                  type: string
                #                  secret info requeired
                secretRef:
                  description: SrereteRef
                  properties:
                    name:
                      description: secretName
                      type: string
                    namespace:
                      description: secretNamespace
                      type: string
                  required:
                    - name
                    - namespace
                  type: object
              required:
                - secretRef
              type: object
            status:
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: { }
