apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openstackresources.doslab.io
spec:
  group: doslab.io
  names:
    kind: OpenstackResource
    plural: openstackresources
    singular: openstackresource
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Resource ID
          jsonPath: .spec.id
          name: ID
          type: string
        - description: Resource Status
          jsonPath: .spec.status
          name: Status
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          description: Resource is the Schema for the openstack resource API
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: spec defines the desired state of openstack server
              properties:
                #                  meta info
                id:
                  type: string
                status:
                  type: string
                #                  secret info requeired
              type: object
            status:
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: { }
