apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openstackloadbalancers.doslab.io
spec:
  group: doslab.io
  names:
    kind: OpenstackLoadBalancer
    plural: openstackloadbalancers
    singular: openstackloadbalancer
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: LoadBalancer ID
          jsonPath: .spec.id
          name: ID
          type: string
        - description: strategy
          jsonPath: .spec.strategy
          name: Strategy
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          description: LoadBalancer is the Schema for the openstack server group API
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: spec defines the desired state of openstack server group
              properties:
                domain:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                lifeCycle:
                  description: request to be execute
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                #                  meta info
                id:
                  type: string
                #                  secret info requeired
                strategy:
                  type: string
                secretRef:
                  description: SrereteRef
                  properties:
                    name:
                      description: secretName
                      type: string
                    namespace:
                      description: secretNamespace
                      type: string
                  required:
                    - name
                    - namespace
                  type: object
              required:
                - secretRef
              type: object
            status:
              type: object

          type: object
      served: true
      storage: true
      subresources:
        status: {}
