apiVersion: v1
kind: Namespace
metadata:
  name: cloudctl-ns
  labels:
    project: cloudctl
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudctl-sa
  namespace: cloudctl-ns
  labels:
    project: cloudctl
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: cloudctl-sa
  name: cloudctl-ns
  namespace: cloudctl-ns
  labels:
    project: cloudctl
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudctl-cr
  namespace: cloudctl-ns
  labels:
    project: cloudctl
rules:
  - apiGroups:
      - doslab.io
    resources:
      - openstackimages
      - openstackservers
      - openstacknetworks
      - openstackrouters
      - openstacksnapshots
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - nonResourceURLs:
      - /
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudctl-crb
  labels:
    project: cloudctl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudctl-cr
subjects:
  - kind: ServiceAccount
    name: cloudctl-sa
    namespace: cloudctl-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudctl-systemdiscovery-crb
  labels:
    project: cloudctl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:discovery
subjects:
  - kind: ServiceAccount
    name: cloudctl-sa
    namespace: cloudctl-ns