apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openstackimages.doslab.io
spec:
  group: doslab.io
  names:
    kind: OpenstackRouter
    plural: openstackrouters
    singular: openstackrouter
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: ID is the unique identifier for the router.
          jsonPath: .spec.id
          name: ID
          type: string
        - description: Name is the human-readable display name for the router.
          jsonPath: .spec.domain.name
          name: Name
          type: string
        - description:  Status indicates whether or not a router is currently operational.
          jsonPath: .spec.domain.status
          name: Status
          type: string
        - description: AdminStateUp is the administrative state of the router.
          jsonPath: .spec.domain.admin_state_up
          name: AdminStateUp
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          description: router is the Schema for the openstack router API
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: spec defines the desired state of openstack route
              properties:
                domain:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                lifeCycle:
                  description: request to be execute
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                #                  meta info
                id:
                  type: string
                #                  secret info requeired
                secretRef:
                  description: SrereteRef
                  properties:
                    name:
                      description: secretName
                      type: string
                    namespace:
                      description: secretNamespace
                      type: string
                  required:
                    - name
                    - namespace
                  type: object
              required:
                - secretRef
              type: object
            status:
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: { }
