apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openstacksnapshots.doslab.io
spec:
  group: doslab.io
  names:
    kind: OpenstackSnapshot
    plural: openstacksnapshots
    singular: openstacksnapshot
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Unique identifier.
          jsonPath: .spec.id
          name: ID
          type: string
        - description: Display name
          jsonPath: .spec.domain.name
          name: Name
          type: string
        - description: Status is the image status. It can be "queued" or "active"
          jsonPath: .spec.domain.status
          name: Status
          type: string
        - description: Display description
          jsonPath: .spec.domain.description
          name: Description
          type: string
        - description: ID of the Volume from which this Snapshot was created
          jsonPath: .spec.domain.volume_id
          name: VolumeID
          type: string
        - description: Size of Snapshot, inGB
          jsonPath: .spec.domain.size
          name: Size
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          description: snapshot is the Schema for the openstack snapshot API
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: spec defines the desired state of openstack snapshot
              properties:
                domain:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                lifeCycle:
                  description: request to be execute
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                #                  meta info
                id:
                  type: string
                #                  secret info requeired
                secretRef:
                  description: SrereteRef
                  properties:
                    name:
                      description: secretName
                      type: string
                    namespace:
                      description: secretNamespace
                      type: string
                  required:
                    - name
                    - namespace
                  type: object
              required:
                - secretRef
              type: object
            status:
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: { }
